---
# copyright Utrecht University

yoda_deployment_user: yodadeployment

yoda_version: development
irods_php_version: "{{ yoda_version }}"
codeigniter_version: "{{ yoda_version }}"
codeigniter_environment: development

yoda_portal_fqdn: portal.yoda.test
update_portal: yes
yoda_php_encryption_key: dummy
yoda_public_dir: /var/www/yoda/yoda-portal/public

# Yoda portal source
portal_sources:
  - repo: "https://github.com/UtrechtUniversity/CodeIgniter.git"
    dest: /var/www/yoda/CodeIgniter
    version: "{{ codeigniter_version }}"
    install_scripts:
  - repo: "https://github.com/UtrechtUniversity/irods-php.git"
    dest: /var/www/yoda/irods-php
    version: "{{ irods_php_version }}"
  - repo: "https://github.com/UtrechtUniversity/yoda-portal.git"
    dest: /var/www/yoda/yoda-portal
    version: "{{ yoda_version }}"

# Yoda modules
modules:
  - name: group-manager
    repo: "https://github.com/UtrechtUniversity/yoda-portal-group-manager.git"
    dest: /var/www/yoda/yoda-portal/modules/group-manager
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: research
    repo: "https://github.com/UtrechtUniversity/yoda-portal-research.git"
    dest: /var/www/yoda/yoda-portal/modules/research
    version: "feature/json-metadata"
    install_scripts: yes
  - name: statistics
    repo: "https://github.com/UtrechtUniversity/yoda-portal-statistics.git"
    dest: /var/www/yoda/yoda-portal/modules/statistics
    version: "{{ yoda_version }}"
    install_scripts: no

# iRODS configuration.
irods_default_resc: irodsResc              # iRODS default resource name
irods_authentication_scheme: Native        # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_icat_fqdn: icat.yoda.test             # iRODS iCAT fully qualified domain name (FQDN)
irods_icat_port: 1247

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt
