---
# copyright Utrecht University

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# iRODS resource server rpm location and checksum
irods_resource:
  package: irods-resource-4.1.11
  url: ftp://ftp.renci.org/pub/irods/releases/4.1.11/centos7
  filename: irods-resource-4.1.11-centos7-x86_64.rpm
  checksum: sha1:721655f3b3482285974e85ed1c66a3f979156389

# iRODS configuration.
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_icat_fqdn: icat.yoda.test
irods_authentication_scheme: Native        # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_port_range_begin: 20000
irods_port_range_end: 20199
irods_icat_port: 1247
irods_service_account: irods
irods_vault_directory: /var/lib/irods/Vault
irods_control_plane_port: 1248
irods_schema_uri: https://schemas.irods.org/configuration

# OpenSSL configuration
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_dhparams: dhparams.pem
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt
