---
# copyright Utrecht University

galaxy_info:
  author: Lazlo Westerhof
  description: Install iRODS database plugin
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
    - name: CentOS
      version: 7


dependencies:
  - postgresql
