---
# copyright Utrecht University

galaxy_info:
  author: Lazlo Westerhof
  description: Configure iRODS composable resources
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
  - name: CentOS
    version: 7


dependencies:
- python-irodsclient
