---
# copyright Utrecht University

- name: Checkout rulesets from github
  become_user: "{{ irods_service_account }}"
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/irods/{{ item.name }}"
    version: "{{ item.version }}"
    update: "{{ update_rulesets }}"
  with_items: "{{ rulesets }}"
  when: "'repo' in item"
  register: repochanges


- name: Stop cron service before installing Yoda rulesets
  service:
    name: crond
    state: stopped


- name: Run make install for each ruleset
  become_user: "{{ irods_service_account }}"
  become: yes
  make:
    chdir: "/etc/irods/{{ item.0.name }}"
    target: install
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"


- name: Ensure all rulesets are in server config
  become_user: "{{ irods_service_account }}"
  become: yes
  irods_rulesets:
    config_path: "/etc/irods/server_config.json"
    rulesets: "{{ rulesets | map(attribute='ruleset_name') | list  }}"
  when: not ansible_check_mode


- name: Wait until iRODS server is ready to receive requests
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: 'ils /{{ irods_zone }}/home'
  register: ils
  until: ils | succeeded
  retries: 5
  delay: 10


- name: Start cron service after installing Yoda rulesets
  service:
    name: crond
    state: started


- include_tasks: "{{ ruleset.name }}.yml"
  with_items: "{{ rulesets }}"
  loop_control:
    loop_var: ruleset
  when: ruleset.install_scripts and install_rulesets
