---
# copyright Utrecht University

yoda_deployment_user: yodadeployment
yoda_version: development
yoda_eus_fqdn: eus.yoda.test

# External User Service configuration
eus_api_secret: PLACEHOLDER

eus_db_host: localhost
eus_db_port: 5432
eus_db_name: extuser
eus_db_user: extuser
eus_db_password: PLACEHOLDER
eus_db_user_table: users

eus_smtp_host: PLACEHOLDER
eus_smtp_port: 587
eus_smtp_user: PLACEHOLDER
eus_smtp_password: PLACEHOLDER
eus_smtp_from_name: Yoda External User Service
eus_smtp_from_address: PLACEHOLDER
eus_smtp_replyto_name: PLACEHOLDER
eus_smtp_replyto_address: PLACEHOLDER

eus_mail_template: uu

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt
