---
# copyright Utrecht University

# iRODS configuration.
irods_service_account: irods
irods_zone: tempZone                       # The name of the iRODS Zone

# Test configuration.
test_password: test

# Following users are created by Ansible as iRODS and UNIX users.
test_users:
  - name: researcher
    password: '{{ test_password }}'
    type: rodsuser
  - name: viewer
    password: '{{ test_password }}'
    type: rodsuser
  - name: groupmanager
    password: '{{ test_password }}'
    type: rodsuser
  - name: datamanager
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladmingroup
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladmincategory
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladminpriv
    password: '{{ test_password }}'
    type: rodsuser
  - name: technicaladmin
    password: '{{ test_password }}'
    type: rodsadmin
  - name: testuseradd
    password: '{{ test_password }}'
    type: rodsuser
  - name: testuserdel
    password: '{{ test_password }}'
    type: rodsuser
  - name: bodmember
    password: '{{ test_password }}'
    type: rodsuser

# Following users are created as iRODS users only.
eus_test_users:
  - name: yodaresearcher@gmail.com
  - name: yodadatamanager@gmail.com

# Following users are created in the regressiontest and need to be removed only.
created_by_ta_users:
  - name: createnewuser
  - name: yodaexternaluser@gmail.com

test_groups:
  - groupName: research-default-0
    category: default-0
    subcategory: default-0
    dataClassification: unspecified
  - groupName: datamanager-default-0
    category: default-0
    subcategory: default-0
    dataClassification:
  - groupName: research-default-1
    category: default-1
    subcategory: default-1
    dataClassification: unspecified
  - groupName: datamanager-default-1
    category: default-1
    subcategory: default-1
    dataClassification:
  - groupName: research-browse
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-initial
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-initial1
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: datamanager-initial
    category: initial
    subcategory: initial
    dataClassification:
  - groupName: grp-intake-initial
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: grp-datamanager-initial
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: grp-vault-initial
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: grp-intake-test
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: grp-datamanager-test
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: grp-vault-test
    category: intake-intake
    subcategory: intake-intake
    dataClassification: unspecified
  - groupName: research-deletegroup
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-updateproperties
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-epicpid
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-mdtest
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-mdtestvault
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-notification
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-notpreservable
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-oaipmh
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-process1
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-process2
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-process3
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-processfordatacite
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-revisions
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-search
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-datarequest
    category: initial
    subcategory: initial
    dataClassification: unspecified
  - groupName: research-teststatistics1
    category: teststatistics
    subcategory: teststatistics
    dataClassification: unspecified
  - groupName: research-teststatistics2
    category: teststatistics
    subcategory: teststatistics
    dataClassification: unspecified
  - groupName: datamanager-teststatistics
    category: teststatistics
    subcategory: teststatistics
    dataClassification:
  - groupName: research-nodmprocess
    category: nodminitial
    subcategory: nodminitial
    dataClassification: unspecified
  - groupName: datarequests-research-board-of-directors
    category: datarequests
    subcategory: research
    dataClassification: unspecified
  - groupName: datarequests-research-datamanagers
    category: datarequests
    subcategory: research
    dataClassification: unspecified

test_groupusers:
  - groupName: research-default-0
    user: functionaladminpriv
    role: manager

  - groupName: datamanager-default-0
    user: functionaladminpriv
    role: manager

  - groupName: research-default-1
    user: functionaladminpriv
    role: manager

  - groupName: datamanager-default-1
    user: functionaladminpriv
    role: manager

  - groupName: datarequests-research-board-of-directors
    user: bodmember
    role: manager

  - groupName: datarequests-research-datamanagers
    user: datamanager
    role: manager

  - groupName: priv-category-add
    user: functionaladminpriv
    role: manager
  - groupName: priv-category-add
    user: functionaladmincategory
    role: manager

  - groupName: priv-group-add
    user: functionaladminpriv
    role: manager
  - groupName: priv-group-add
    user: functionaladmingroup
    role: manager

  - groupName: research-browse
    user: functionaladminpriv
    role: manager
  - groupName: research-browse
    user: researcher
    role: normal

  - groupName: research-initial
    user: functionaladminpriv
    role: manager
  - groupName: research-initial
    user: groupmanager
    role: manager
  - groupName: research-initial
    user: researcher
    role: normal
  - groupName: research-initial
    user: viewer
    role: reader
  - groupName: research-initial
    user: testuserdel
    role: normal

  - groupName: research-initial1
    user: functionaladminpriv
    role: manager
  - groupName: research-initial1
    user: groupmanager
    role: normal
  - groupName: research-initial1
    user: researcher
    role: normal
  - groupName: research-initial1
    user: viewer
    role: normal

  - groupName: datamanager-initial
    user: functionaladminpriv
    role: manager
  - groupName: datamanager-initial
    user: datamanager
    role: normal
  - groupName: datamanager-initial
    user: yodadatamanager@gmail.com
    role: normal

  - groupName: research-deletegroup
    user: functionaladminpriv
    role: manager
  - groupName: research-deletegroup
    user: researcher
    role: normal
  - groupName: research-deletegroup
    user: viewer
    role: reader
  - groupName: research-deletegroup
    user: groupmanager
    role: manager
  - groupName: research-deletegroup
    user: datamanager
    role: normal

  - groupName: grp-intake-initial
    user: researcher
    role: normal
  - groupName: grp-intake-initial
    user: groupmanager
    role: manager
  - groupName: grp-intake-initial
    user: datamanager
    role: normal

  - groupName: grp-datamanager-initial
    user: datamanager
    role: manager

  - groupName: grp-intake-test
    user: researcher
    role: normal
  - groupName: grp-intake-test
    user: groupmanager
    role: manager
  - groupName: grp-intake-test
    user: datamanager
    role: normal

  - groupName: grp-datamanager-test
    user: datamanager
    role: manager

  - groupName: research-updateproperties
    user: functionaladminpriv
    role: manager
  - groupName: research-updateproperties
    user: groupmanager
    role: manager
  - groupName: research-updateproperties
    user: researcher
    role: normal
  - groupName: research-updateproperties
    user: viewer
    role: reader

  - groupName: research-epicpid
    user: functionaladminpriv
    role: manager
  - groupName: research-epicpid
    user: groupmanager
    role: manager
  - groupName: research-epicpid
    user: researcher
    role: normal
  - groupName: research-epicpid
    user: viewer
    role: reader

  - groupName: research-mdtest
    user: functionaladminpriv
    role: manager
  - groupName: research-mdtest
    user: groupmanager
    role: manager
  - groupName: research-mdtest
    user: researcher
    role: normal
  - groupName: research-mdtest
    user: viewer
    role: reader

  - groupName: research-mdtestvault
    user: functionaladminpriv
    role: manager
  - groupName: research-mdtestvault
    user: groupmanager
    role: manager
  - groupName: research-mdtestvault
    user: researcher
    role: normal
  - groupName: research-mdtestvault
    user: viewer
    role: reader

  - groupName: research-notification
    user: functionaladminpriv
    role: manager
  - groupName: research-notification
    user: groupmanager
    role: manager
  - groupName: research-notification
    user: yodaresearcher@gmail.com
    role: normal
  - groupName: research-notification
    user: researcher
    role: normal
  - groupName: research-notification
    user: viewer
    role: reader

  - groupName: research-notpreservable
    user: functionaladminpriv
    role: manager
  - groupName: research-notpreservable
    user: groupmanager
    role: manager
  - groupName: research-notpreservable
    user: yodaresearcher@gmail.com
    role: normal
  - groupName: research-notpreservable
    user: researcher
    role: normal
  - groupName: research-notpreservable
    user: viewer
    role: reader

  - groupName: research-oaipmh
    user: functionaladminpriv
    role: manager
  - groupName: research-oaipmh
    user: groupmanager
    role: manager
  - groupName: research-oaipmh
    user: researcher
    role: normal
  - groupName: research-oaipmh
    user: viewer
    role: reader

  - groupName: research-process1
    user: functionaladminpriv
    role: manager
  - groupName: research-process1
    user: groupmanager
    role: manager
  - groupName: research-process1
    user: researcher
    role: normal
  - groupName: research-process1
    user: viewer
    role: reader

  - groupName: research-process2
    user: functionaladminpriv
    role: manager
  - groupName: research-process2
    user: groupmanager
    role: manager
  - groupName: research-process2
    user: researcher
    role: normal
  - groupName: research-process2
    user: viewer
    role: reader

  - groupName: research-process3
    user: functionaladminpriv
    role: manager
  - groupName: research-process3
    user: groupmanager
    role: manager
  - groupName: research-process3
    user: researcher
    role: normal
  - groupName: research-process3
    user: viewer
    role: reader

  - groupName: research-processfordatacite
    user: functionaladminpriv
    role: manager
  - groupName: research-processfordatacite
    user: groupmanager
    role: manager
  - groupName: research-processfordatacite
    user: researcher
    role: normal
  - groupName: research-processfordatacite
    user: viewer
    role: reader

  - groupName: research-revisions
    user: functionaladminpriv
    role: manager
  - groupName: research-revisions
    user: groupmanager
    role: manager
  - groupName: research-revisions
    user: researcher
    role: normal
  - groupName: research-revisions
    user: viewer
    role: reader

  - groupName: research-search
    user: functionaladminpriv
    role: manager
  - groupName: research-search
    user: groupmanager
    role: manager
  - groupName: research-search
    user: researcher
    role: normal
  - groupName: research-search
    user: viewer
    role: reader

  - groupName: research-teststatistics1
    user: functionaladminpriv
    role: manager

  - groupName: research-teststatistics2
    user: functionaladminpriv
    role: manager

  - groupName: datamanager-teststatistics
    user: functionaladminpriv
    role: manager

  - groupName: research-nodmprocess
    user: functionaladminpriv
    role: manager
  - groupName: research-nodmprocess
    user: groupmanager
    role: manager
  - groupName: research-nodmprocess
    user: researcher
    role: normal
  - groupName: research-nodmprocess
    user: viewer
    role: reader

  - groupName: research-datarequest
    user: datamanager
    role: reader
  - groupName: research-datarequest
    user: groupmanager
    role: manager
  - groupName: research-datarequest
    user: researcher
    role: normal

deletion_research_groups:
  - research: browse
  - research: deletegroup
  - research: escapecharsinfolders
  - research: i1
  - research: initial
  - research: initial1
  - research: epicpid
  - research: mdtest
  - research: mdtestvault
  - research: nodmprocess
  - research: notification
  - research: notpreservable
  - research: oaipmh
  - research: process1
  - research: process2
  - research: process3
  - research: processfordatacite
  - research: r1
  - research: research
  - research: recreateresearch
  - research: recreateresearch3
  - research: revisions
  - research: search
  - research: teststatistics1
  - research: teststatistics2
  - research: tovaultnodm
  - research: tovaultwithdm
  - research: updateproperties

deletion_datamanager_groups:
  - datamanager: frontendtest
  - datamanager: initial
  - datamanager: teststatistics
  - datamanager: nodminitial
  - datamanager: newtovault
  - datamanager: charescaping
deletion_grp_groups:
  - grp: datamanager-initial
  - grp: datamanager-test
  - grp: g1
  - grp: intake-initial
  - grp: intake-test
  - grp: vault-initial
  - grp: vault-test
deletion_intake_groups:
  - intake: i1
  - intake: recreateintake
  - intake: researchintake

reset_tiers:
  - dev001
  - dev001_1
  - dev001_2
  - dev001_p1
  - dev001_p2
  - irodsResc
  - irodsRescRepl
  - bundleResc
