---
# copyright Utrecht University

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# davrods RPM location and checksum
davrods:
  package: davrods-4.2.3_1.4.1-1
  url: https://github.com/UtrechtUniversity/davrods/releases/download/4.2.3_1.4.1
  filename: davrods-4.2.3_1.4.1-1.rpm
  checksum: sha256:e80982ec9b000316abb4246eb185f862997004872aca49244ce281b7ca502344

yoda_davrods_fqdn: data.yoda.test           # Yoda Davrods WebDAV fully qualified domain name (FQDN)
yoda_davrods_port: 443

yoda_davrods_anonymous_fqdn: public.data.yoda.test
yoda_davrods_anonymous_port: 443

yoda_portal_fqdn: portal.yoda.test          # Yoda Portal fully qualified domain name (FQDN)

# iRODS configuration.
irods_icat_fqdn: icat.yoda.test
irods_authentication_scheme: PAM           # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_default_resc: irodsResc              # iRODS default resource name
irods_icat_port: 1247
irods_ssl_verify_server: cert

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt
openssl_dhparams: dhparams.pem
