---
# copyright Utrecht University

- include_tasks: password_protect.yml
  with_inventory_hostnames:
    - 'icats:&{{ instance }}'
  loop_control:
    loop_var: icat_host


- name: Create iCAT database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ irods_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0


- name: Create iRods database user
  become_user: postgres
  become: yes
  postgresql_user:
    db: "{{ irods_database_name }}"
    name: "{{ irods_database_user }}"
    password: "{{ irods_database_password }}"
    priv: ALL
