---
# copyright Utrecht University

landingpages_root: /var/www/landingpages

yoda_moai_user: moai
yoda_moai_home: /var/www/moai

yoda_public_host: combined.yoda.test   # Yoda public host
yoda_public_fqdn: public.yoda.test     # Yoda public fully qualified domain name (FQDN)
yoda_public_port: 443

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_crt_signed_and_chain: localhost_and_chain.crt
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt

change_firewall: true
