---
# copyright Utrecht University

yoda_version: development
irods_service_account: irods

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# Zabbix postgres rpm location and checksum
zabbix_postgres:
  package: libzbxpgsql-1.1.0-1
  url: https://github.com/UtrechtUniversity/yoda-zabbix/releases/download/1.3-beta/
  filename: libzbxpgsql-1.1.0-1.el7.x86_64.rpm
  checksum: sha256:b6e7051bb41aceec9edfaa20189e83ab5403ae4cd8d5b67bfffe20f30d93fb23

# Zabbix postgres database user (CREATE ROLE zabbix WITH LOGIN NOSUPERUSER, NOCREATEDB, NOCREATEROLE
# and (GRANT CONNECT ON DATABASE "ICAT" TO zabbix)
# Zabbix configuration
zabbix_database_name: ICAT
irods_database_name: ICAT
eus_db_name: extuser
zabbix_database_user: zabbix


zabbix_server: 192.168.50.20

repo_only: no  # Only download packages from repos.