---
# copyright Utrecht University
# zabbixagent tasks

- name: Check if Zabbix agent is installable from repository
  yum:
    list: '{{ zabbix_agent.package }}'
  register: zabbix_agent_repo


- name: Download Zabbix agent rpm
  get_url:
    url: '{{ zabbix_agent.url }}/{{ zabbix_agent.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ zabbix_agent.filename }}'
    checksum: '{{ zabbix_agent.checksum }}'
  when: not zabbix_agent_repo.results


- name: Install Zabbix agent from downloaded rpm
  package:
    name: '{{ rpm_dest_dir }}/{{ zabbix_agent.filename }}'
    state: present
  when: not zabbix_agent_repo.results


- name: Ensure Zabbix agent rpm is installed
  package:
    name: '{{ zabbix_agent.package }}'
    state: present
  when: zabbix_agent_repo.results


- name: Enable the Zabbix agent service
  service:
    name: zabbix-agent
    enabled: yes
    use: service


- name: Allow Zabbix agent to start
  selinux_permissive:
    name: zabbix_agent_t
    permissive: true
  when: ansible_selinux


- name: Generate Zabbix agent PSK
  shell: openssl rand -hex 256 > /etc/zabbix/zabbix_agentd.psk
    creates=/etc/zabbix/zabbix_agentd.psk
  when: not ansible_check_mode


- name: Ensure right file ownership on zabbix_agentd.psk
  file:
    path: /etc/zabbix/zabbix_agentd.psk
    owner: zabbix
    group: zabbix
    mode: 0600


- name: Configure Zabbix agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0600
  notify: Restart Zabbix agent


