---
# copyright Utrecht University

########################
# Ansible configuration
########################
ansible_user: vagrant                             # Administrative user on instance for Ansible
ansible_ssh_private_key_file: vagrant/ssh/vagrant # Path to private key file of administrative user

#####################
# Yoda configuration
#####################
instance: allinone                                 # Name of Yoda instance, as defined in hosts file
yoda_version: development                          # Git branch, for example: development or release-1.2
codeigniter_environment: development               # CodeIgniter environment: development, testing, acceptance or production
yoda_portal_fqdn: portal.yoda.test                 # Yoda Portal fully qualified domain name (FQDN)
yoda_davrods_fqdn: data.yoda.test                  # Yoda Davrods WebDAV fully qualified domain name (FQDN)
yoda_davrods_anonymous_fqdn: public.data.yoda.test # Yoda Davrods anonymous WebDAV fully qualified domain name (FQDN)

######################
# Yoda Portal modules
######################
modules:
  - name: group-manager
    repo: "https://github.com/UtrechtUniversity/yoda-portal-group-manager.git"
    dest: /var/www/yoda/yoda-portal/modules/group-manager
    version: "{{ yoda_version }}"
  - name: research
    repo: "https://github.com/UtrechtUniversity/yoda-portal-research.git"
    dest: /var/www/yoda/yoda-portal/modules/research
    version: "{{ yoda_version }}"
  - name: statistics
    repo: "https://github.com/UtrechtUniversity/yoda-portal-statistics.git"
    dest: /var/www/yoda/yoda-portal/modules/statistics
    version: "{{ yoda_version }}"
  - name: intake
    repo: "https://github.com/UtrechtUniversity/yoda-portal-intake.git"
    dest: /var/www/yoda/yoda-portal/modules/intake
    version: "{{ yoda_version }}"

######################
# iRODS configuration
######################
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_database_user: irodsdb               # The iRODS database username
irods_database_password: irodsdev          # The password for the iRODS database username
irods_authentication_scheme: Native        # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_icat_fqdn: combined.yoda.test        # iRODS iCAT fully qualified domain name (FQDN)
irods_database_fqdn: combined.yoda.test    # iRODS database fully qualified domain name (FQDN)
irods_resource_fqdn: combined.yoda.test    # iRODS resource fully qualified domain name (FQDN)
irods_default_resc: irodsResc              # iRODS default resource name
irods_ssl_verify_server: none              # Verify TLS certificate, use 'cert' for acceptance and production
irods_resources:
  - name: dev001_1
    host: "{{ irods_icat_fqdn }}"
    vault_path: /var/lib/irods/Vault1_1
    resource_type: unixfilesystem

  - name: dev001_2
    resource_type: unixfilesystem
    host: "{{ irods_icat_fqdn }}"
    vault_path: /var/lib/irods/Vault1_2

  - name: dev001_p1
    resource_type: passthru
    children:
      - dev001_1

  - name: dev001_p2
    resource_type: passthru
    children:
      - dev001_2

  - name: dev001
    resource_type: random
    children:
      - dev001_p1
      - dev001_p2

  - name: irodsResc
    resource_type: random
    children:
      - dev001

  - name: dev002_1
    resource_type: unixfilesystem
    host: "{{ irods_resource_fqdn }}"
    vault_path: /var/lib/irods/Vault2_1

  - name: dev002_p1
    resource_type: passthru
    children:
      - dev002_1

  - name: dev002
    resource_type: random
    children:
      - dev002_p1

  - name: irodsRescRepl
    resource_type: random
    children:
      - dev002

########################
# Ruleset configuration
########################
rulesets:
  - name: irods-ruleset-youth-cohort
    repo: https://github.com/UtrechtUniversity/irods-ruleset-youth-cohort.git
    ruleset_name: rules-yc
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: irods-ruleset-i-lab
    repo: https://github.com/UtrechtUniversity/irods-ruleset-i-lab.git
    ruleset_name: rules-i-lab
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: irods-ruleset-research
    repo: https://github.com/UtrechtUniversity/irods-ruleset-research.git
    ruleset_name: rules-research
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: irods-ruleset-uu
    repo: https://github.com/UtrechtUniversity/irods-ruleset-uu.git
    ruleset_name: rules-uu
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: core
    ruleset_name: core
    path: /etc/irods/core.re
    install_scripts: no

################################
# Research module configuration
################################
default_yoda_schema: test      # Default Yoda XML scheme: default or test
enable_revisions: 1            # Enable revisions: yes (1) or no (0)
revision_strategy: B           # Revision strategy: A, B, J or Simple
yoda_random_id_length: 6       # Length of random ID to add to persistent identifier
yoda_prefix: UU01              # Prefix for internal portion of persistent identifier
update_rulesets: yes           # Update already installed rulesets with git
update_schemas: 1              # Update already installed schemas, formelements and stylesheets: yes (1) or no (0)

#####################
# Mail notifications
#####################
send_notifications: 0               # Enable notifications: yes (1) or no (0)
sender_email: noreply@yoda.test     # Sender email address
reply_to: noreply@yoda.test         # Reply-To email address
smtp_server: PLACEHOLDER            # SMTP server to send mail to
smtp_username: PLACEHOLDER          # SMTP server username
smtp_password: PLACEHOLDER          # SMTP server password

#########################
# DataCite Configuration
#########################
datacite_username: PLACEHOLDER          # DataCite username
datacite_password: PLACEHOLDER          # DataCite password
datacite_prefix: 10.5072                # DataCite DOI prefix
datacite_server: mds.test.datacite.org  # DataCite server URI

###########################
# PAM Radius configuration
###########################
# server, shared secret, timeout (s)
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

#######################
# Zabbix configuration
#######################
zabbix_server: PLACEHOLDER

############################
# Public host configuration
############################
yoda_public_host: combined.yoda.test   # Yoda public host
yoda_public_fqdn: public.yoda.test     # Yoda public fully qualified domain name (FQDN)

# Yoda public upload private key (base64 encoded)
# ssh-keygen -t ed25519 -> base64
upload_priv_key: |
  LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
  QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhP
  UUFBQUNDTGlhY01DT2xPZzNpSFg4VXdYOHpWUk11cFB2Y2NyTTdmQUNodU9WMi80UUFBQUpoQTVj
  YTlRT1hHCnZRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ0xpYWNNQ09sT2czaUhYOFV3WDh6VlJN
  dXBQdmNjck03ZkFDaHVPVjIvNFEKQUFBRUFtRng0MmVDSDBYOHFHaXpmUmFpcFJWa3MzcVo1OWda
  SU92TUJkZy85SnhZdUpwd3dJNlU2RGVJZGZ4VEJmek5WRQp5NmsrOXh5c3p0OEFLRzQ1WGIvaEFB
  QUFEbWx5YjJSelFHTnZiV0pwYm1Wa0FRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZB
  VEUgS0VZLS0tLS0K

# Yoda public upload public key (base64 encoded)
upload_pub_key: |
  c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUl1SnB3d0k2VTZEZUlkZnhUQmZ6
  TlZFeTZrKzl4eXN6dDhBS0c0NVhiL2ggaXJvZHNAY29tYmluZWQK
