---
# copyright Utrecht University

rolename: irods-icat

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# iRODS iCAT rpm location and checksum
irods_icat:
  package: irods-icat-4.1.11
  url: ftp://ftp.renci.org/pub/irods/releases/4.1.11/centos7
  filename: irods-icat-4.1.11-centos7-x86_64.rpm
  checksum: sha1:cd6a450477c9db51a6d1cc1dcc565c5eecf3d58d

# iRODS database plugin rpm location and checksum
irods_db:
  package: irods-database-plugin-postgres-1.11
  url: ftp://ftp.renci.org/pub/irods/releases/4.1.11/centos7
  filename: irods-database-plugin-postgres-1.11-centos7-x86_64.rpm
  checksum: sha1:5872b49bd75b6ff882a7e265cf5a502b9ca51a74

# iRODS configuration.
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_database_fqdn: database.yoda.test
irods_database_name: ICAT
irods_database_port: 5432
irods_database_user: irodsdb               # The iRODS database username
irods_database_password: irodsdev          # The password for the iRODS database username
irods_authentication_scheme: PAM           # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_port_range_begin: 20000
irods_port_range_end: 20199
irods_icat_port: 1247
irods_service_account: irods
irods_vault_directory: /var/lib/irods/Vault
irods_control_plane_port: 1248
irods_schema_uri: https://schemas.irods.org/configuration
irods_ssl_verify_server: cert

# PAM configuration.
pam_fail_delay: 1000000                    # PAM fail delay in micro-seconds
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

# External Users configuration
external_users: True
yoda_eus_fqdn: eus.yoda.test
eus_api_secret: PLACEHOLDER

# OpenSSL configuration
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_dhparams: dhparams.pem
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt
