---
# copyright Utrecht University

- name: Ensure Yoda landingpages root is world readable
  file:
    path: '{{ landingpages_root }}'
    mode: 0755
    owner: '{{ yoda_inbox_user }}'
    group: 'apache'
    state: directory


- name: Ensure inbox user exists
  user:
    name: '{{ yoda_inbox_user }}'


- name: Add upload user pub key to authorized_keys of inbox
  authorized_key:
    user: '{{ yoda_inbox_user }}'
    key: '{{ upload_pub_key | b64decode }}'
    state: present


- name: Ensure Yoda landingpage static file directories are present
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ landingpages_root }}/static/css/'
    - '{{ landingpages_root }}/static/img/'
    - '{{ landingpages_root }}/static/js/'


- name: Ensure old Yoda landingpage static files are absent
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ landingpages_root }}/static/css/yoda-landingpage.css'
    - '{{ landingpages_root }}/static/js/jquery-3.2.1.min.js'
    - '{{ landingpages_root }}/static/js/main.js'


- name: Ensure Yoda landingpage static files are present
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
  with_items:
    - src: 'index.html'
      dest: '{{ landingpages_root }}/index.html'
    - src: 'css/bootstrap.min.css'
      dest: '{{ landingpages_root }}/static/css/bootstrap.min.css'
    - src: 'css/uu.css'
      dest: '{{ landingpages_root }}/static/css/uu.css'
    - src: 'img/logo.svg'
      dest: '{{ landingpages_root }}/static/img/logo.svg'
    - src: 'img/logo_footer.svg'
      dest: '{{ landingpages_root }}/static/img/logo_footer.svg'
