---
# copyright Utrecht University

rolename: irods-icat

# iRODS configuration.
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_database_fqdn: database.yoda.test
irods_database_name: ICAT
irods_database_port: 5432
irods_database_user: irodsdb               # The iRODS database username
irods_database_password: irodsdev          # The password for the iRODS database username
irods_authentication_scheme: PAM           # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_default_resc: irodsResc              # iRODS default resource name
irods_port_range_begin: 20000
irods_port_range_end: 20199
irods_icat_port: 1247
irods_service_account: irods
irods_vault_directory: /var/lib/irods/Vault
irods_control_plane_port: 1248
irods_schema_uri: https://schemas.irods.org/configuration
irods_ssl_verify_server: cert

# PAM configuration.
pam_fail_delay: 1000000                    # PAM fail delay in micro-seconds
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

# External Users configuration
external_users: True
external_users_domain_filter: uu.nl
eus_api_fqdn: eus.yoda.test
eus_api_port: 8443
eus_api_secret: PLACEHOLDER

# OpenSSL configuration
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_dhparams: dhparams.pem
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt

# OpenID Connect configuration
oidc_userinfo_uri: ''

# Service type. Possible values: 'sysv' and 'systemd'
irods_service_type: 'systemd'

# The max number of open files is only effective when
# irods_service_type has been set to 'systemd'.
irods_max_open_files: 131072

# Data Access Tokens
enable_tokens: false                               # Enable data access tokens for webDAV and iCommands
token_database: /etc/irods/yoda-ruleset/tokens.db  # Location of the database that contain the tokens

# OpenSearch module configuration
enable_open_search: false                          # Enable OpenSearch module
